name: Deploy dev

on:
  workflow_dispatch: {}

jobs:
  deploy-dev:
    concurrency: dev
    uses: mikhailadvani/experiments/.github/workflows/environment-deploy.yml@main
    with:
      cluster_name: "dev"
    secrets:
      ENV_NAME: ${{ secrets.ENV_NAME }}
