name: Deploy prod

on:
  workflow_dispatch: {}

jobs:
  deploy-prod:
    concurrency: prod
    uses: mikhailadvani/experiments/.github/workflows/environment-deploy.yml@main
    with:
      cluster_name: "prod"
    secrets:
      ENV_NAME: ${{ secrets.ENV_NAME }}
