name: Deploy infrastructure

on:
  push:
    branches: [ "*" ]

permissions: read-all

jobs:
  repo-lint:
    uses: mikhailadvani/experiments/.github/workflows/terraform-repo-lint.yml@main

  deploy-backend:
    concurrency: backend
    uses: mikhailadvani/experiments/.github/workflows/terraform-deploy.yml@main
    with:
      directory: "environments/backend"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: repo-lint

  deploy-global:
    concurrency: global
    uses: mikhailadvani/experiments/.github/workflows/terraform-deploy.yml@main
    with:
      directory: "environments/global" 
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: deploy-backend
