name: Deploy infrastructure

on:
  push:
    branches: [ "*" ]

permissions: read-all

jobs:
  call-a:
    uses: mikhailadvani/experiments/.github/workflows/echo.yml@main
    with:
      username: a
    concurrency: a
  call-b:
    uses: mikhailadvani/experiments/.github/workflows/echo.yml@main
    with:
      username: b
    concurrency: b
    needs: call-a
  call-c:
    uses: mikhailadvani/experiments/.github/workflows/echo.yml@main
    with:
      username: c
    concurrency: c
    needs: call-b
  call-d:
    uses: mikhailadvani/experiments/.github/workflows/echo.yml@main
    with:
      username: d
    concurrency: d
    needs: call-c
