name: Deploy infrastructure

on:
  push:
    branches: [ "*" ]

permissions: read-all

jobs:
  call-workflow-passing-data:
    uses: mikhailadvani/experiments/.github/workflows/echo.yml@main
    with:
      username: mona
