name: Deploy infrastructure

on:
  push:
    branches: [ "*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.0.11
    steps:
      - uses: actions/checkout@v2

      - name: "terraform-version"
        run: |
          terraform version

      - uses: mikhailadvani/experiments/.github/workflows/echo.yml
        with:
          username: "mikhail"
      
      # - uses: ./.github/actions/deploy-terraform
      #   with:
      #     directory: "environments/backend"
      #     # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     # AWS_REGION: "eu-west-1"

      # - uses: ./.github/actions/deploy-terraform
      #   with:
      #     directory: "environments/global"
      #     # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     # AWS_REGION: "eu-west-1"
