name: Deploy infrastructure

on:
  push:
    branches: [ "*" ]

permissions: read-all

runs_on: &runs_on
  runs-on: ubuntu-latest
  container: hashicorp/terraform:1.0.11

jobs:
  repo-lint: 
    <<: *runs_on
    uses: mikhailadvani/experiments/.github/workflows/terraform-repo-lint.yml@main

  deploy-backend:
    <<: *runs_on
    uses: mikhailadvani/experiments/.github/workflows/terraform-deploy.yml@main
    with:
      directory: "environments/backend"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: repo-lint

  deploy-global:
    <<: *runs_on
    uses: mikhailadvani/experiments/.github/workflows/terraform-deploy.yml@main
    with:
      directory: "environments/global" 
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: deploy-backend
