on:
  workflow_call: {}

jobs:
  terraform-repo-lint:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.0.11
    steps:
      - uses: actions/checkout@v2

      - name: "terraform-version"
        run: |
          terraform version

      - name: "terraform-lint"
        run: |
          terraform fmt -recursive -check
